### ISSUE TITLE
Emoji incorrecto en el Tablón de Insignias

### ISSUE THREAD

**Issue by skcode7** [malandrinersdev/lego.js#1]
En el Tablón de insignias se presenta bien el contador, pero el emoji no es el correcto.
![imagen](https://user-images.githubusercontent.com/55223838/117545482-92ccc200-afeb-11eb-90ea-304170ab89a0.png)

Me gustaría resolverlo!

**Comment by delineas** [comment]
Adelante con ello :)

Lanza una Pull Request con el cambio cuando quieras. Si tienes dudas, pregunta ;)

Nota: No lo tenemos documentado todavía, pero ya hay un Dockerfile y un docker-compose.yml para que puedas arrancar en local tu entorno de desarrollo.

**Comment by skcode7** [comment]
Me costó correrlo, pero luego vi que el error era en la URL 🤦🏼‍♂️

**Comment by sergioedo** [comment]
Genial @skcode7, muy bien visto y genial tu contribución, ya está mergeado! 
Por cierto, he visto que mejoraste también el título de la página 👍 👍  Para issues más complejas, te recomiendo hacer los mínimos cambios relativos a la issue, para que sea más sencillo luego hacer el merge, pero en este caso no aplica y más siendo el primero en contribuir (esto huele a insignia...🥇), adelante las PRs! Gracias de nuevo!

**Comment by skcode7** [comment]
Toda la razón @sergioedo lo tendré en cuenta para los próximos PR.

Seguiré atento para colaborar en lo que pueda.
